apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logos-pvc
  namespace: logos-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
